[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "33vQPdG6AQCQ5QGHQjqJra49n4a64PjZLEYgEXdX6T39"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bash scripts/anchor-test.sh"
